-- Import: Botschaften (voller Ersatz für die betroffenen Personen, damit keine Duplikate entstehen)
DELETE FROM messages WHERE for_name IN ('Andreea','Florian','Oliver');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Danke, dass du unter der Woche so viel stemmst 💜');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Du hältst hier alles zusammen – das sehe ich 😘');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Ohne dich würde hier nichts laufen. Danke! 🌷');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Job, Kinder, Haushalt und gut aussehen, wie machst du das!? 🤷');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Während ich noch überlege, hast du''s schon erledigt. Danke ☺️');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Ohne dich gäb''s hier nur Toast und Nudeln 😛');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Du bist die fleissigste Bufniţă weit und breit 💪');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Andreea, Meisterin im "Ich mach das schnell noch" 🚀');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Wenn Aufräumen eine Sportart wäre, hättest du längst ein Trikot mit Sponsoren 🥇');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'Küche blitzblank – irgendwo klatscht gerade ein Marie-Kondo-Fanclub 😉');
INSERT INTO messages (for_name, text) VALUES ('Andreea', 'vv');
INSERT INTO messages (for_name, text) VALUES ('Andreea', '11-11');
INSERT INTO messages (for_name, text) VALUES ('Andreea', '😘');
INSERT INTO messages (for_name, text) VALUES ('Andreea', '🦄🦄');
INSERT INTO messages (for_name, text) VALUES ('Oliver', 'Nicht vergessen - du hast auch noch einen Vollzeitjob');
INSERT INTO messages (for_name, text) VALUES ('Oliver', 'Aufgabe gründlich erledigt?');
INSERT INTO messages (for_name, text) VALUES ('Oliver', 'Allen recht getan ist eine Kunst die niemand kann 🥳');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Müll rausgebracht, bevor er ein Eigenleben entwickelt hat. Danke');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Job erledigt – deine zukünftige WG wird dich dafür lieben, versprochen');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Kein Seufzen, kein ''gleich'', einfach gemacht. Respekt');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Das ging schneller als deine Antwort auf eine WhatsApp. Beeindruckend');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Erledigt, bevor jemand nachfragen musste. Notiert, im positiven Sinne');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Du hast bewiesen: geht auch ohne Diskussion. Merken wir uns');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Nicht dein Lieblingsteil vom Tag, das wissen wir. Danke, dass du''s trotzdem machst');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'erledigt, bevor die nächste Gaming-Session startet – Zeitmanagement-Skills: legendary');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Kein Respawn nötig – gleich beim ersten Versuch fertig geworden');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Mission complete. Kein Loot, aber immerhin saubere Wohnung');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Sogar in den Ferien erledigt, wo eigentlich gar nix Pflicht sein sollte. Anerkennung');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Ausgeschlafen UND die Aufgabe erledigt? Zwei Bosse an einem Tag besiegt');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Ferienmodus an, trotzdem was geschafft – das nennt man Skill-Diversität');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'AFK warst du heute woanders – hier warst du on point');
INSERT INTO messages (for_name, text) VALUES ('Florian', 'Achievement unlocked: Haushalt UND Gaming in einer Woche');
